openapi: 3.0.1

info:
  title: "The LIdea project"
  description: "REST API docs for The LIdea project"
  contact:
    name: "Ilya Facelzz"
    email: "ilya.facelzz+the-lidea@gmail.com"
  version: "1"

paths:
  /specialists:
    get:
      tags: [Specialists]
      summary: List of specialists
      description: List of all specialists in the system
      parameters:
        - $ref: '#/components/parameters/PagePaginationParameter'
        - $ref: '#/components/parameters/PerPagePaginationParameter'
        - $ref: '#/components/parameters/SpecialityIdParameter'
      responses:
        200:
          description: List of specialists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpecialistListItem'
        422:
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

components:
  parameters:

    PagePaginationParameter:
      in: query
      name: page
      required: false
      schema:
        $ref: '#/components/schemas/PageParameter'

    PerPagePaginationParameter:
      in: query
      name: page
      required: false
      schema:
        $ref: '#/components/schemas/PerPageParameter'

    SpecialityIdParameter:
      in: query
      name: specialityId
      required: false
      schema:
        $ref: '#/components/schemas/Id'

  schemas:

    Id:
      type: integer
      minimum: 1
      example: 1

    PageParameter:
      type: integer
      minimum: 1

    PerPageParameter:
      type: integer
      minimum: 1

    SpecialistName:
      type: string
      maxLength: 256

    SpecialityName:
      type: string
      maxLength: 128

    SpecialistListItem:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/SpecialistName'
        speciality:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/Id'
            name:
              $ref: '#/components/schemas/SpecialityName'
          required:
            - id
            - name
      required:
        - id
        - name
        - speciality

    ValidationErrorResponse:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          minProperties: 1
          additionalProperties:
            type: array
            minItems: 1
            items:
              type: string
