version: '3'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        - WWWUSER
        - WWWGROUP
    container_name: '${APP_NAME}-app'
    tty: true
    ports:
      - '${APP_PORT:-80}:80'
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - tidea-network
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    container_name: '${APP_NAME}-pgsql'
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    ports:
      - '${FORWARD_DB_PORT:-54320}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
        - ./docker/pgsql/data:/var/lib/postgresql/data
        - ./docker/pgsql/logs:/logs
    networks:
      - tidea-network

  pgadmin:
      image: dpage/pgadmin4
      container_name: '${APP_NAME}-pgadmin'
      environment:
          PGADMIN_DEFAULT_EMAIL: 'ilya.facelzz@gmail.com'
          PGADMIN_DEFAULT_PASSWORD: 'password'
      ports:
          - '81:80'
      networks:
          - tidea-network


  pgsql-test:
    image: postgres
    container_name: '${APP_NAME}-pgsql-test'
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    ports:
      - '${TEST_FORWARD_DB_PORT:-54321}:5432'
    environment:
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
        - ./docker/pgsql-test/data:/var/lib/postgresql/data
        - ./docker/pgsql-test/logs:/logs
    networks:
      - tidea-network

networks:
  tidea-network:
    driver: bridge
